Sportsball a = Sportsball.Baseball;
		Sportsball b = Sportsball.Tenisball;
		Console.WriteLine(a);
		Console.WriteLine(b);
		GetSportsball z = new GetSportsball();
		GetSportsball y = new GetSportsball();
		z.Basketball = "Hello";
		y.Basketball = " world!";
		Console.Write(z.Basketball);
        Console.WriteLine(y.Basketball);